#!/bin/sh
#Assorted insanity by M0WUT and M0IKY to make a better WSPR decoder

if test "$#" -ne 3
then
	echo "Usage is of the format ./wspr-rx callsign locator frequency(in MHz)"
	echo "Example: \"./wspr-rx m0wut jo02af 14.0956 \""
	exit 1
fi

arecord -B 2000000 -f S16_LE -r 48000 --duration=114 -q -D hw:0,0 -c 2 -t wav - | #Record audio for 114 seconds
sox -t wav - -c 1 -r 12000 -t wav - | #trim audio to 12k mono
wsprd -wf "$3" /dev/stdin | #run WSPR decoder
tee /dev/tty | #print decoded callsign to console
curl -sF allmept=@- -F call="$1" -F grid="$2" wsprnet.org/meptspots.php | #Upload spots
grep spot | #Select line in wspr server reply that contains whether the spots were uploaded
tr '<br>' '  \r\n'  #remove html junk





